version: '3.8'

services:

  web:
    build: ./
    command: >
      sh -c "python manage.py migrate
      && cat create_users.py | python3 manage.py shell
      && cat create_bugs.py | python3 manage.py shell
      && python manage.py runserver 0.0.0.0:8000"

    volumes:
      - ./:/usr/src/bug-tracker/
    ports:
      - 8000:8000
    env_file:
      - ./.env